#!/bin/bash
pwd='/home/git/rep/'
name=&1
if [ -d "/home/git/rep/$name".git"" ];then
echo Repository alredy exist. Aborted.
else
cd /home/git/rep/
git init --bare $name".git"
cd $name".git"
cd hooks/
rm *
mkdir /home/git/deploy/$name".git"
echo '#!/bin/bash' > post-receive
echo "GIT_NAME="$name".git" >> post-receive
cat /home/git/script/post-receive >> post-receive                                                                     
chmod +x post-receive
cd ..
git update-server-info
cd ..
sudo chmod 777 $name".git"
#sudo chown -R www-data $name".git"
sudo chown -R root $name".git"
echo "Repository sucessfuly created in :$pwd$name.git"
echo "You can set a new remote with: git remote add origin ssh://root@51.75.27.87:/home/git/rep/$name.git"
fi